-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 09:00:28 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_name
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_name` ;

-- -----------------------------------------------------
-- Schema db_name
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_name` DEFAULT CHARACTER SET utf8 ;
USE `db_name` ;

-- -----------------------------------------------------
-- Table `db_name`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`user_role` ;

CREATE TABLE IF NOT EXISTS `db_name`.`user_role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`user` ;

CREATE TABLE IF NOT EXISTS `db_name`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL COMMENT '	',
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `db_name`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`site` ;

CREATE TABLE IF NOT EXISTS `db_name`.`site` (
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_site_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_site_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_name`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`content_type` ;

CREATE TABLE IF NOT EXISTS `db_name`.`content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`content` ;

CREATE TABLE IF NOT EXISTS `db_name`.`content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_content_content_type1_idx` (`content_type_id` ASC),
  INDEX `fk_content_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_content_content_type1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `db_name`.`content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_name`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`layout` ;

CREATE TABLE IF NOT EXISTS `db_name`.`layout` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `section_count` INT NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_layout_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_layout_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_name`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`page` ;

CREATE TABLE IF NOT EXISTS `db_name`.`page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `layout_id` INT NOT NULL,
  `homepage` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `fk_page_user1_idx` (`user_id` ASC),
  INDEX `fk_page_layout1_idx` (`layout_id` ASC),
  CONSTRAINT `fk_page_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_name`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_page_layout1`
    FOREIGN KEY (`layout_id`)
    REFERENCES `db_name`.`layout` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`user_details` ;

CREATE TABLE IF NOT EXISTS `db_name`.`user_details` (
  `user_id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  INDEX `fk_user_details_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_details_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_name`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_name`.`page_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_name`.`page_content` ;

CREATE TABLE IF NOT EXISTS `db_name`.`page_content` (
  `page_id` INT NOT NULL,
  `content_id` INT NOT NULL,
  `sequence` INT NULL,
  `section_num` INT NULL,
  INDEX `fk_page_has_content_content1_idx` (`content_id` ASC),
  INDEX `fk_page_has_content_page1_idx` (`page_id` ASC),
  CONSTRAINT `fk_page_has_content_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `db_name`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_page_has_content_content1`
    FOREIGN KEY (`content_id`)
    REFERENCES `db_name`.`content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERT USER_ROLE VALUES 
INSERT INTO USER_ROLE VALUES (1, 'Admin');
INSERT INTO USER_ROLE VALUES (2, 'Member');

-- INSERT CONTENT_TYPE VALUES
INSERT INTO CONTENT_TYPE VALUES (1, 'CONTENT');
INSERT INTO CONTENT_TYPE VALUES (2, 'HEADER');
INSERT INTO CONTENT_TYPE VALUES (3, 'NAVIGATION');
INSERT INTO CONTENT_TYPE VALUES (4, 'FOOTER');

-- INSERT USER CREDENTIALS
INSERT INTO USER VALUES (1, 'ad_username', 'ad_password', null, 1);

-- INSERT SITE DETAILS
INSERT INTO SITE VALUES ('st_name', 1, null);
